// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdritjldksrbshllwojp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkcml0amxka3NyYnNobGx3b2pwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5Mjc0NTksImV4cCI6MjA2MjUwMzQ1OX0._YN2wg-BDVjmpa_1H_yPaR27TZRkwDi3EnsrwRkYzYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);